[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "conservation"
version = "0.1.0"
description = "Evolutionary Conservation of Amino Acids and Codons"
authors = [
    { name="Hanjun Lee", email="hanjun_lee@hms.harvard.edu" }
]
readme = "README.md"
requires-python = ">=3.5"
license = {text = "MIT"}
dependencies = [
    "numpy",
    "pandas",
    "biopython",
    "scipy",
    "matplotlib",
    "tqdm"
]

[project.urls]
Homepage = "https://github.com/hanjunlee21/conservation"
Repository = "https://github.com/hanjunlee21/conservation"

[project.scripts]
conservation = "conservation.commands:main"
